"""temp_migration

Revision ID: 2da0dc469be8
Revises: 32b1054a69e3
Create Date: 2025-01-07 21:36:44.563306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da0dc469be8'
down_revision: Union[str, None] = '32b1054a69e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Updates the token column type to String(64) in three authentication-related tables.
    
    Alters the `token` column in the `activation_tokens`, `password_reset_tokens`, and `refresh_tokens` tables from `VARCHAR(255)` to `String(64)`, maintaining the non-nullable constraint.
    """
    op.alter_column('activation_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Reverts the token column type changes in three tables to VARCHAR(255).
    
    Restores the `token` column in `activation_tokens`, `password_reset_tokens`, and `refresh_tokens` tables from `String(64)` back to `VARCHAR(255)`, maintaining the non-nullable constraint.
    """
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('activation_tokens', 'token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
