from routes.movies import router as movie_router
from routes.accounts import router as accounts_router
from routes.profiles import router as profiles_router
from routes.shopping_cart import router as shopping_cart_router
from routes.payments import router as payments_router
from routes.orders import router as orders_router
from routes.extra_functionality_movie import router as extra_functionality_movie_router
from routes.comments import router as comments_router
from routes.users import router as users_router
