name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint (flake8)
        run: poetry run flake8 .
      - name: Type check (mypy)
        run: poetry run mypy .
      - name: Run tests
        run: poetry run pytest --cov=.
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: iSevenpwnz/Online-Cinema-Project

      - name: Notify Discord про статус CI
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            CI ${{ job.status }} для ${{ github.repository }} на гілці ${{ github.ref }}.
            Автор: ${{ github.actor }}
            Pull request: ${{ github.event.pull_request.html_url || 'N/A' }}
